### ISSUE TITLE
How to do this plugin in Ionic-Capacitor?

### ISSUE THREAD

**Issue by lapisanlangit** [Cap-go/capacitor-social-login#19]
I have tried this plugin with but this step
in costructor :
` initializeApp() {
    this.platform.ready().then(async () => {
      await SocialLogin.initialize({
        google: {
          webClientId: 'aabbcc',
        },
      });
     });
`
button Login click :
` const res = await SocialLogin.login({
      provider: 'google',
      options: {
        scopes: ['email', 'profile'],
      },
    });
`
and then what next? how to get response?

**Comment by WcaleNieWolny** [comment]
I recommend reading the [setup_google.md](https://github.com/Cap-go/capacitor-social-login/blob/main/docs/setup_google.md).

After you login, you can get the JWT using [getAuthorizationCode](https://github.com/Cap-go/capacitor-social-login?tab=readme-ov-file#getauthorizationcode). Then, you can send this JWT to your server to validate the users identify.

**Comment by lapisanlangit** [comment]
thans for your reply @WcaleNieWolny . i have followed the instruction, and debug with

`console.log(res.response)`

but i have an error :

`No Google accounts available. Please add a Google account to your device and try again`

what wrong with that?

**Comment by WcaleNieWolny** [comment]
I am working on this issue as we speak. `No Google accounts available` is not a difficult fix and in 30 min there should be a new release fixing it

**Comment by WcaleNieWolny** [comment]
@lapisanlangit I just pushed a fix: https://github.com/Cap-go/capacitor-social-login/commit/cb387747c8a49d400322092c10d952225997651b

**Comment by lapisanlangit** [comment]
are this fixing already push on npmjs.com @WcaleNieWolny ? i have tried npm install from this githup repo, build app but get an error.

package.json
`"@capgo/capacitor-social-login": "github:Cap-go/capacitor-social-login"`

ionic capacitor build android :
Cannot find module '@capgo/capacitor-social-login' or its corresponding type declarations.

**Comment by lapisanlangit** [comment]
thank you @WcaleNieWolny  i will wait this github repo updated on npmjs.com...  I give up with codetrix studio for google auth, i have tried that's lib for a week and not get good result... i wish with your library can solve the problem.. thank you

**Comment by WcaleNieWolny** [comment]
I just pushed https://github.com/Cap-go/capacitor-social-login/commit/2794aad3492eee5ac3ecebd6d018ee5b24d128c4

It should compile now and the CI/CD should release the lib on npm soon

**Comment by WcaleNieWolny** [comment]
![image](https://github.com/user-attachments/assets/70e05ca8-c0c6-4313-a330-b89eb485bbad)

@lapisanlangit I did push a version to NPM

**Comment by lapisanlangit** [comment]
thank you @WcaleNieWolny, version 0.0,39 already in npmjs.com. I have tried and "Choose an account" has opened, then i choose one account, but still have an error :  `Google Sign-In failed: activity is cancelled by the user`. how to solve that?

**Comment by WcaleNieWolny** [comment]
@lapisanlangit that would mean that you clicked outside of the modal. Can you record a video showing the error happening?

**Comment by lapisanlangit** [comment]
This is rather difficult to make video.. this is several screen capture : 
 
![Screenshot 2024-10-06 114022](https://github.com/user-attachments/assets/daf97777-6803-4073-ad5d-939f3bb716d3)
![jumb2](https://github.com/user-attachments/assets/bf76fae0-b062-4675-bee2-1bdec0e3a0fd)
![jumb3](https://github.com/user-attachments/assets/8e2d69e8-9922-494f-8a6e-985c586a0729)

**Comment by WcaleNieWolny** [comment]
and you are sure that you clicked `agree and share`?

**Comment by lapisanlangit** [comment]
yes

**Comment by WcaleNieWolny** [comment]
Is your google client published in google or are you still using development accounts?

**Comment by WcaleNieWolny** [comment]
Let me try to reproduce your error

**Comment by lapisanlangit** [comment]
this is still in environment development...I am using my device  same Wifi with my laptop. and my SHA1 already put in console.cloud.google

![image](https://github.com/user-attachments/assets/50d42ae8-8f34-4678-ab4f-2686cbca3b70)
![image](https://github.com/user-attachments/assets/ac6013ce-f33f-483f-93e9-42befe4ff894)

**Comment by WcaleNieWolny** [comment]
![image](https://github.com/user-attachments/assets/64ce2541-ad9e-4129-9c90-f93c5ee3fedd)

This SO answer would suggest that you didn't configure the plugin correctly

**Comment by WcaleNieWolny** [comment]
Here are the 2 posts I could find about this error

- https://stackoverflow.com/questions/77717346/androidx-credentials-exceptions-getcredentialcancellationexception-activity-is
- https://stackoverflow.com/questions/77028602/credentialmanager-with-googleid-always-cancelled

**Comment by WcaleNieWolny** [comment]
This might be tricky, but here are some steps I would recommend for debuging:

A) Ensure that you are using the **WEB** client id and that your code looks similar to this
```ts
  await SocialLogin.initialize({
    google: {
      webClientId: '673324426943-avl4v9ubdas7a0u7igf7in03pdj1dkmg.apps.googleusercontent.com',  
    }
  })
  const response = await SocialLogin.login({
    provider: 'google',
    options: {}
  })
 ```
 
 B) Ensure that you have the valid sha1. If you use android studio development build, you should run `./gradlew signInReport`. [This is explained by the docs](https://github.com/Cap-go/capacitor-social-login/blob/main/docs/setup_google.md) If you are using a keystore to sign your app, you can run `keytool -keystore path-to-debug-or-production-keystore -list -v`.

**Comment by lapisanlangit** [comment]
Oh my god, it finally worked! Thank you @WcaleNieWolny … I can going to next step now. I spent 1-2 weeks with other libraries and couldn’t get it to work. Thanks for your help!

**Comment by WcaleNieWolny** [comment]
No problem! I am glad that it works 😄
